"""add_title_and_type_to_notification

Revision ID: fcbd2287eafb
Revises: 16f193f5f2df
Create Date: 2026-03-16 11:41:44.377086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fcbd2287eafb'
down_revision: Union[str, Sequence[str], None] = '16f193f5f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('event_id', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('title', sa.String(), nullable=False))
    op.add_column('notifications', sa.Column('notification_type', sa.String(), nullable=True))
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_event_id'), 'notifications', ['event_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_event_id'), table_name='notifications')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('notifications', 'notification_type')
    op.drop_column('notifications', 'title')
    op.drop_column('notifications', 'event_id')
    # ### end Alembic commands ###
