"""Initial Core Schema

Revision ID: 24b526b8b35e
Revises: 
Create Date: 2026-02-28 19:04:04.961457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b526b8b35e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('thumbnail', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('requires_certificate', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trainings'))
    )
    op.create_index(op.f('ix_trainings_created_by_id'), 'trainings', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_trainings_id'), 'trainings', ['id'], unique=False)
    op.create_index(op.f('ix_trainings_tenant_id'), 'trainings', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_trainings_title'), 'trainings', ['title'], unique=False)
    op.create_table('enrollments',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('training_version_id', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_url', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_enrollments_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments'))
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_tenant_id'), 'enrollments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enrollments_training_id'), 'enrollments', ['training_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('modules',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_modules_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules'))
    )
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_index(op.f('ix_modules_tenant_id'), 'modules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_modules_training_id'), 'modules', ['training_id'], unique=False)
    op.create_table('training_histories',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_training_histories_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_histories'))
    )
    op.create_index(op.f('ix_training_histories_id'), 'training_histories', ['id'], unique=False)
    op.create_index(op.f('ix_training_histories_tenant_id'), 'training_histories', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_histories_training_id'), 'training_histories', ['training_id'], unique=False)
    op.create_table('chapters',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('VIDEO', 'PDF', 'SCORM', 'QUIZ', 'RICH_TEXT', name='chapter_content_type'), nullable=False),
    sa.Column('content_data', sa.JSON(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_chapters_module_id_modules')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_chapters_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters'))
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    op.create_index(op.f('ix_chapters_module_id'), 'chapters', ['module_id'], unique=False)
    op.create_index(op.f('ix_chapters_tenant_id'), 'chapters', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_chapters_training_id'), 'chapters', ['training_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('chapter_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='user_progress_status'), nullable=False),
    sa.Column('training_version_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_user_progress_chapter_id_chapters')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_user_progress_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_progress')),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uix_user_chapter_progress')
    )
    op.create_index(op.f('ix_user_progress_chapter_id'), 'user_progress', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_tenant_id'), 'user_progress', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_progress_training_id'), 'user_progress', ['training_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_training_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_tenant_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_chapter_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_chapters_training_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_tenant_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_module_id'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_training_histories_training_id'), table_name='training_histories')
    op.drop_index(op.f('ix_training_histories_tenant_id'), table_name='training_histories')
    op.drop_index(op.f('ix_training_histories_id'), table_name='training_histories')
    op.drop_table('training_histories')
    op.drop_index(op.f('ix_modules_training_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_tenant_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_training_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_tenant_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_trainings_title'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_tenant_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_id'), table_name='trainings')
    op.drop_index(op.f('ix_trainings_created_by_id'), table_name='trainings')
    op.drop_table('trainings')
    # ### end Alembic commands ###
