"""create_training_assignments

Revision ID: 8cbc4abfc23a
Revises: c1d63d314a0f
Create Date: 2026-03-04 16:25:25.838976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbc4abfc23a'
down_revision: Union[str, Sequence[str], None] = 'c1d63d314a0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_assignments',
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('group_id', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_training_assignments_training_id_trainings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_training_assignments'))
    )
    op.create_index(op.f('ix_training_assignments_group_id'), 'training_assignments', ['group_id'], unique=False)
    op.create_index(op.f('ix_training_assignments_id'), 'training_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_training_assignments_tenant_id'), 'training_assignments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_training_assignments_training_id'), 'training_assignments', ['training_id'], unique=False)
    op.create_index(op.f('ix_training_assignments_user_id'), 'training_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_assignments_user_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_training_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_tenant_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_id'), table_name='training_assignments')
    op.drop_index(op.f('ix_training_assignments_group_id'), table_name='training_assignments')
    op.drop_table('training_assignments')
    # ### end Alembic commands ###
