"""add tags structure_type recertification attempt_id video_progress fields

Revision ID: a7a622543aab
Revises: f4a5b6c7d8e9
Create Date: 2026-05-12 23:06:16.104247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7a622543aab'
down_revision: Union[str, Sequence[str], None] = 'f4a5b6c7d8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enrollments_certificate_id'), table_name='enrollments')
    op.add_column('quiz_attempts', sa.Column('enrollment_attempt_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('training_assignments', sa.Column('completion_lock', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('training_assignments', sa.Column('attempt_id', sa.Integer(), server_default='1', nullable=False))
    op.add_column('trainings', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('trainings', sa.Column('structure_type', sa.String(length=20), server_default='flat', nullable=False))
    op.add_column('trainings', sa.Column('requires_recertification', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('trainings', sa.Column('recertification_period_days', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_trainings_template_id'), table_name='trainings')
    op.add_column('user_progress', sa.Column('resume_position_seconds', sa.Integer(), nullable=True))
    op.add_column('user_progress', sa.Column('milestone_25', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_progress', sa.Column('milestone_50', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_progress', sa.Column('milestone_75', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_progress', sa.Column('milestone_100', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('user_progress', sa.Column('attempt_id', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_progress', 'attempt_id')
    op.drop_column('user_progress', 'milestone_100')
    op.drop_column('user_progress', 'milestone_75')
    op.drop_column('user_progress', 'milestone_50')
    op.drop_column('user_progress', 'milestone_25')
    op.drop_column('user_progress', 'resume_position_seconds')
    op.create_index(op.f('ix_trainings_template_id'), 'trainings', ['template_id'], unique=False)
    op.drop_column('trainings', 'recertification_period_days')
    op.drop_column('trainings', 'requires_recertification')
    op.drop_column('trainings', 'structure_type')
    op.drop_column('trainings', 'tags')
    op.drop_column('training_assignments', 'attempt_id')
    op.drop_column('training_assignments', 'completion_lock')
    op.drop_column('quiz_attempts', 'enrollment_attempt_id')
    op.create_index(op.f('ix_enrollments_certificate_id'), 'enrollments', ['certificate_id'], unique=False)
    # ### end Alembic commands ###
