"""add_training_is_active

Revision ID: c1d63d314a0f
Revises: 24b526b8b35e
Create Date: 2026-03-04 13:33:58.503399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d63d314a0f'
down_revision: Union[str, Sequence[str], None] = '24b526b8b35e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainings', 'is_active')
    # ### end Alembic commands ###
