"""certificate_tables

Revision ID: f3e4d5c6b7a8
Revises: 524e6ea3ab21
Create Date: 2026-03-21 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3e4d5c6b7a8'
down_revision: Union[str, Sequence[str], None] = '524e6ea3ab21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_templates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate_templates'))
    )
    op.create_index(op.f('ix_certificate_templates_id'), 'certificate_templates', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_templates_is_active'), 'certificate_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_certificate_templates_tenant_id'), 'certificate_templates', ['tenant_id'], unique=False)
    
    op.create_table('certificates',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('training_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['certificate_templates.id'], name=op.f('fk_certificates_template_id_certificate_templates')),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], name=op.f('fk_certificates_training_id_trainings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificates'))
    )
    op.create_index(op.f('ix_certificates_certificate_number'), 'certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_certificates_id'), 'certificates', ['id'], unique=False)
    op.create_index(op.f('ix_certificates_template_id'), 'certificates', ['template_id'], unique=False)
    op.create_index(op.f('ix_certificates_tenant_id'), 'certificates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_certificates_training_id'), 'certificates', ['training_id'], unique=False)
    op.create_index(op.f('ix_certificates_user_id'), 'certificates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certificates_user_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_training_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_tenant_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_template_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_id'), table_name='certificates')
    op.drop_index(op.f('ix_certificates_certificate_number'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_certificate_templates_tenant_id'), table_name='certificate_templates')
    op.drop_index(op.f('ix_certificate_templates_is_active'), table_name='certificate_templates')
    op.drop_index(op.f('ix_certificate_templates_id'), table_name='certificate_templates')
    op.drop_table('certificate_templates')
    # ### end Alembic commands ###
